### ISSUE TITLE
Custom form validation

### ISSUE THREAD

**Issue by lucalenardi** [feincms/form_designer#12]
Hi,

what's considered the best way to add custom form validation? It could be useful to add a "honeypot" form of spam detection, but I cannot find a simple (by design) method to do it.

Thanks!

**Comment by michaelkuty** [comment]
@lucalenardi FIELD_TYPES was ignored because when model is created his choices was populated. This was fixed in #17 using lazy loading
I think that this issue is obsolete and could be closed.

**Comment by matthiask** [comment]
Thanks!
