### ISSUE TITLE
Maximum recursion depth exceeded in the jsonize function

### ISSUE THREAD

**Issue by ivan-sysoi** [feincms/form_designer#15]
Hello.

I try to use form_designer with python 3.4.0 and django 1.8.2, feincms 1.11.0.
When I add new form and select option `Send e-mail`, it raises exception.

RuntimeError at /admin/form_designer/form/add/
maximum recursion depth exceeded while calling a Python object
Exception Location:	site-packages/form_designer/admin.py in jsonize, line 55

When I select option `Save form submission`, everything is ok.

**Comment by ivan-sysoi** [comment]
I have added ```and not isinstance(v, str)``` and now it works for me.

```python
def jsonize(v):
    if isinstance(v, dict):
        return dict((i1, jsonize(i2)) for i1, i2 in v.items())
    if hasattr(v, '__iter__') and not isinstance(v, str):
        return [jsonize(i) for i in v]
    if isinstance(v, Model):
        return v.pk
    return v
```

**Comment by matthiask** [comment]
Thanks for the report. Indeed, the result of `hasattr('bla', '__iter__')` differs on Python 2 and 3.

**Comment by matthiask** [comment]
v0.6.2 fixes this problem. Thanks again!
